\set ON_ERROR_STOP on

CREATE TABLE pk_benchmark.event_log_uuid (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    actor_id bigint NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamptz NOT NULL,
    source_system text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT event_log_uuid_pkey PRIMARY KEY (id),
    CONSTRAINT event_log_uuid_actor_id_positive CHECK (actor_id > 0),
    CONSTRAINT event_log_uuid_event_type_check
        CHECK (event_type IN ('created', 'updated', 'deleted', 'viewed')),
    CONSTRAINT event_log_uuid_source_system_not_blank
        CHECK (btrim(source_system) <> ''),
    CONSTRAINT event_log_uuid_payload_is_object
        CHECK (jsonb_typeof(payload) = 'object')
);

COMMENT ON TABLE pk_benchmark.event_log_uuid IS
    'Event log variant with UUID primary key generated by gen_random_uuid().';
COMMENT ON COLUMN pk_benchmark.event_log_uuid.id IS
    'Primary key for the UUID experiment branch.';

CREATE INDEX event_log_uuid_occurred_at_idx
    ON pk_benchmark.event_log_uuid (occurred_at);

CREATE INDEX event_log_uuid_actor_id_id_idx
    ON pk_benchmark.event_log_uuid (actor_id, id);
