\set ON_ERROR_STOP on

CREATE TABLE pk_benchmark.event_log_bigserial (
    id bigserial NOT NULL,
    actor_id bigint NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamptz NOT NULL,
    source_system text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT event_log_bigserial_pkey PRIMARY KEY (id),
    CONSTRAINT event_log_bigserial_actor_id_positive CHECK (actor_id > 0),
    CONSTRAINT event_log_bigserial_event_type_check
        CHECK (event_type IN ('created', 'updated', 'deleted', 'viewed')),
    CONSTRAINT event_log_bigserial_source_system_not_blank
        CHECK (btrim(source_system) <> ''),
    CONSTRAINT event_log_bigserial_payload_is_object
        CHECK (jsonb_typeof(payload) = 'object')
);

COMMENT ON TABLE pk_benchmark.event_log_bigserial IS
    'Event log variant with BIGSERIAL primary key generated by a PostgreSQL sequence.';
COMMENT ON COLUMN pk_benchmark.event_log_bigserial.id IS
    'Primary key for the BIGSERIAL experiment branch.';

CREATE INDEX event_log_bigserial_occurred_at_idx
    ON pk_benchmark.event_log_bigserial (occurred_at);

CREATE INDEX event_log_bigserial_actor_id_id_idx
    ON pk_benchmark.event_log_bigserial (actor_id, id);
